import 'dart:ui';

import 'package:flutter/material.dart';

List<Color> colors = [
  Colors.amber,
  Colors.orange,
  Colors.pink.shade200,
  Colors.cyan,
  Colors.blueAccent,
  Colors.deepOrange,
  Colors.lightGreen,
  Colors.tealAccent,
  Colors.indigo.shade300,
  Colors.redAccent,
  Colors.lightBlue,
  Colors.deepPurpleAccent,
  Colors.green.shade700,
  Colors.brown,
  Colors.amber.shade300,
  Colors.purple,
  Colors.yellow,
  Colors.cyanAccent,
  Colors.blue,
  Colors.deepOrangeAccent,
  Colors.grey.shade600,
  Colors.lime,
  Colors.pink,
  Colors.teal.shade500,
  Colors.red,
  Colors.blue.shade700,
  Colors.greenAccent,
  Colors.orange.shade300,
  Colors.deepPurple.shade400,
  Colors.brown.shade300,
  Colors.amberAccent,
  Colors.purpleAccent,
  Colors.pinkAccent,
  Colors.indigoAccent,
  Colors.yellowAccent,
  Colors.limeAccent,
  Colors.grey,
  Colors.red.shade400,
  Colors.lightBlueAccent,
  Colors.teal,
  Colors.lightGreenAccent,
  Colors.cyan.shade300,
  Colors.deepPurple,
  Colors.orangeAccent,
  Colors.purple.shade300,
  Colors.blue.shade300,
  Colors.green.shade400,
  Colors.deepPurpleAccent.shade100,
  Colors.red.shade200,
  Colors.amber.shade100,
  Colors.lightGreen.shade200,
  Colors.pinkAccent.shade100,
  Colors.deepPurpleAccent.shade200,
  Colors.indigo.shade100,
  Colors.limeAccent.shade100,
  Colors.orangeAccent.shade100,
  Colors.brown.shade100,
  Colors.blue.shade100,
  Colors.cyanAccent.shade100,
  Colors.grey.shade200,
  Colors.lightBlueAccent.shade100,
  Colors.purpleAccent.shade100,
  Colors.yellowAccent.shade100,
  Colors.tealAccent.shade100,
  Colors.deepPurple.shade100,
  Colors.greenAccent.shade100,
  Colors.deepOrangeAccent.shade100,
  Colors.teal.shade100,
  Colors.lightGreenAccent.shade100,
  Colors.redAccent.shade100,
  Colors.amberAccent.shade100,
  Colors.lime.shade100,
  Colors.orange.shade100,
  Colors.pink.shade100,
  Colors.cyan.shade100,
  Colors.blueAccent.shade100,
  Colors.deepOrange.shade100,
  Colors.lightBlue.shade100,
  Colors.indigo.shade200,
  Colors.purple.shade200,
  Colors.yellow.shade100,
  Colors.grey.shade100,
  Colors.blue.shade200,
  Colors.greenAccent.shade200,
  Colors.orange.shade200,
  Colors.pink.shade300,
  Colors.cyan.shade200,
  Colors.blueAccent.shade200,
  Colors.deepOrange.shade200,
  Colors.lightBlue.shade200,
  Colors.tealAccent.shade200,
  Colors.indigoAccent.shade200,
  Colors.red.shade300,
  Colors.deepPurple.shade200,
  Colors.brown.shade200,
  Colors.amber.shade200,
  Colors.purpleAccent.shade200,
  Colors.pinkAccent.shade200,
  Colors.grey.shade300,
  Colors.yellowAccent.shade200,
  Colors.limeAccent.shade200,
  Colors.lightGreen.shade300,
  Colors.orangeAccent.shade200,
  Colors.teal.shade200,
  Colors.cyanAccent.shade200,
  Colors.blue.shade300,
  Colors.green.shade500,
  Colors.deepPurpleAccent.shade100,
  Colors.red.shade400,
  Colors.indigo.shade300,
  Colors.lightBlueAccent.shade200,
  Colors.purple.shade300,
  Colors.yellow.shade200,
  Colors.lime.shade200,
  Colors.orange.shade300,
  Colors.pinkAccent.shade400,
  Colors.deepOrangeAccent.shade200,
  Colors.tealAccent.shade200,
  Colors.amberAccent.shade200,
  Colors.blue.shade400,
  Colors.cyan.shade300,
  Colors.deepPurple.shade300,
  Colors.greenAccent.shade200,
  Colors.grey.shade400,
  Colors.lightGreenAccent.shade200,
  Colors.orangeAccent.shade200,
  Colors.purpleAccent.shade400,
  Colors.lightBlueAccent.shade700,
  Colors.teal.shade300,
  Colors.yellowAccent.shade100,
  Colors.red.shade500,
  Colors.pink.shade400,
  Colors.indigoAccent.shade200,
  Colors.blueAccent.shade200,
  Colors.deepOrange.shade300,
  Colors.limeAccent.shade200,
  Colors.brown.shade300,
  Colors.cyanAccent.shade100,
  Colors.deepPurpleAccent.shade400,
  Colors.orange.shade400,
  Colors.amber.shade300,
  Colors.lightGreen.shade400,
  Colors.tealAccent.shade200,
  Colors.purple.shade400,
  Colors.blue.shade500,
  Colors.grey.shade500,
  Colors.green.shade600,
  Colors.red.shade600,
  Colors.pinkAccent.shade400,
  Colors.indigo.shade400,
  Colors.yellow.shade400,
  Colors.lightBlue.shade400,
  Colors.deepOrangeAccent.shade200,
  Colors.orangeAccent.shade400,
  Colors.blueAccent.shade400,
  Colors.cyan.shade400,
  Colors.deepPurpleAccent.shade100,
  Colors.teal.shade400,
  Colors.purpleAccent.shade400,
  Colors.lime.shade400,
  Colors.lightGreenAccent.shade700,
  Colors.amberAccent.shade400,
  Colors.redAccent.shade100,
  Colors.grey.shade600,
  Colors.orange.shade500,
  Colors.pink.shade500,
  Colors.deepPurple.shade500,
  Colors.indigoAccent.shade400,
  Colors.yellowAccent.shade400,
  Colors.tealAccent.shade400,
  Colors.lightBlueAccent.shade400,
  Colors.blue.shade600,
  Colors.cyanAccent.shade400,
  Colors.deepOrange.shade400,
  Colors.limeAccent.shade400,
  Colors.purple.shade500,
  Colors.greenAccent.shade400,
  Colors.brown.shade400,
  Colors.amber.shade400,
  Colors.lightGreen.shade500,
  Colors.red.shade700,
  Colors.teal.shade500,
  Colors.orangeAccent.shade200,
  Colors.grey.shade700,
  Colors.pinkAccent.shade700,
  Colors.blueAccent.shade700,
  Colors.indigo.shade500,
  Colors.deepPurpleAccent.shade700,
  Colors.cyan.shade500,
  Colors.yellow.shade500,
  Colors.lightBlue.shade500,
  Colors.deepOrangeAccent.shade200,
  Colors.lime.shade500,
  Colors.green.shade700,
  Colors.purpleAccent.shade400,
  Colors.tealAccent.shade200,
  Colors.redAccent.shade400,
  Colors.amberAccent.shade400,
  Colors.orange.shade600,
  Colors.lightGreenAccent.shade400,
  Colors.grey.shade800,
  Colors.pink.shade600,
  Colors.blue.shade700,
  Colors.indigoAccent.shade200,
  Colors.deepPurple.shade600,
  Colors.cyanAccent.shade700,
  Colors.yellowAccent.shade200,
  Colors.lightBlueAccent.shade200,
  Colors.teal.shade600,
  Colors.deepOrange.shade500,
  Colors.limeAccent.shade200,
  Colors.greenAccent.shade700,
  Colors.purple.shade600,
  Colors.blueAccent.shade700,
  Colors.red.shade800,
  Colors.amber.shade500,
  Colors.orangeAccent.shade700,
  Colors.tealAccent.shade700,
  Colors.grey.shade900,
  Colors.pinkAccent.shade200,
  Colors.indigo.shade600,
  Colors.deepPurpleAccent.shade700,
  Colors.lightBlue.shade600,
  Colors.cyan.shade600,
  Colors.yellow.shade600,
  Colors.lime.shade600,
  Colors.deepOrangeAccent.shade700,
  Colors.green.shade800,
];

Map<String, Color> categoryColors = {
  'Accounting': Colors.greenAccent,
  'Architecture & Construction': Colors.red,
  'Business': Colors.yellow,
  'Customer Service': Colors.blue,
  'Data Analysis': Colors.indigo,
  'Development - Programming': Colors.green,
  'Design': Colors.pinkAccent,
  'Education & Training': Colors.blue,
  'Environmental Science': Colors.teal,
  'Event Planning': Colors.deepPurple,
  'Financial Planning': Colors.deepOrange,
  'Graphic Design': Colors.purple,
  'Healthcare & Medicine': Colors.purpleAccent,
  'Human Resources': Colors.cyan,
  'Information Technology': Colors.amber,
  'Legal & Compliance': Colors.brown,
  'Logistics & Supply Chain': Colors.lightBlue,
  'Manufacturing & Operations': Colors.lime,
  'Marketing': Colors.deepOrange,
  'Nonprofit Management': Colors.grey,
  'Project Management': Colors.orange,
  'Public Health': Colors.blueGrey,
  'Public Relations': Colors.lightGreen,
  'Quality Assurance': Colors.amber,
  'Research & Development': Colors.lime,
  'Sales & Customer Relations': Colors.orange,
  'Social Media Management': Colors.redAccent,
  'Writing & Editing': Colors.blueGrey

  // Add more categories and colors as needed
};
