List<String> skills = [
  'web design',
  'gardening',
  'automotive mechanic',
  'public speaking',
  'data analysis',
  'graphic design',
  'programming',
  'financial planning',
  'customer service',
  'photography',
  'foreign language proficiency',
  'project management',
  'content writing',
  'marketing',
  'problem-solving',
  'leadership',
  'critical thinking',
  'time management',
  'public relations',
  'networking',
  'social media management',
  'creative writing',
  'negotiation',
  'event planning',
  'research',
  'public health knowledge',
  'sales',
  'teaching',
  'mentoring',
  'conflict resolution',
  'emotional intelligence',
  'database management',
  'software development',
  'cybersecurity',
  'cloud computing',
  'artificial intelligence',
  'machine learning',
  'virtual collaboration',
  'data visualization',
  'public policy analysis',
  'business strategy',
  'financial analysis',
  'entrepreneurship',
  'video editing',
  'audio production',
  'game development',
  'animation',
  'meditation',
  'yoga',
  'nutrition',
  'culinary skills',
  'first aid',
  'interpersonal communication',
  'user experience (UX) design',
  'user interface (UI) design',
  'product management',
  'supply chain management',
  'logistics',
  'business analysis',
  'customer relationship management (CRM)',
  'data entry',
  'virtual assistance',
  'event coordination',
  'fundraising',
  'grant writing',
  'community organizing',
  'nonprofit management',
  'fundamental IT skills',
  'hardware troubleshooting',
  'network administration',
  'system security',
  'technical support',
  'creative thinking',
  'innovation',
  'self-motivation',
  'adaptability',
  'emotional resilience',
  'decision-making',
  'legal research',
  'courtroom advocacy',
  'mediation',
  'contract negotiation',
  'strategic planning',
  'risk management',
  'business development',
  'market research',
  'data analytics',
  'data interpretation',
  'quality assurance',
  'presentation skills',
  'writing',
  'editing',
  'proofreading',
  'content strategy',
  'SEO (Search Engine Optimization)',
  'digital marketing',
  'email marketing',
  'branding',
  'experimental design',
  'statistical analysis',
  'scientific writing',
  'laboratory techniques',
  'communication',
  'community engagement',
  'political strategy',
  'campaign management',
  'international relations',
  'cross-cultural communication',
  'journalism',
  'video production'
];
