List<String> skills = [
  'Anti-semitism',
  'Buddhism',
  'Bullying/Cyber Bullying',
  'Censorship',
  'Children & Youth',
  'Christianity',
  'Civil Rights',
  'Climate Change',
  'Criminal Justice',
  'Crime',
  'Conservation',
  'Democracy',
  'Disability',
  'Disaster Relief',
  'Domestic Violence / Spousal Abuse',
  'Gender',
  'Economic Justice',
  'Education K-12',
  'Education - Higher Education',
  'Elder Care',
  'Environment',
  'Expungement Expertise',
  'Fair Trade',
  'Faith',
  'Gender and Gender Identity',
  'Genocide',
  'Gentrification',
  'GLBT',
  'Globalization',
  'Global Warming',
  'Gun Control',
  'Family Values',
  'First Amendment/Freedom of Speech',
  'Food & Hunger',
  'Foster Care',
  'Hate',
  'Health',
  'Hinduism',
  'Housing & Homelessness',
  'Human Rights',
  'Human Trafficking',
  'Immigration',
  'International Affairs',
  'Information Security',
  'International Affairs',
  'Islam',
  'Islamophobia',
  'Judaism',
  'Labor & Unions',
  'Law Enforcement / Police',
  'Marijuana',
  'Mens Issues',
  'Mental Health',
  'Non-profit Organizations',
  'Parenting',
  'Peace',
  'Politics',
  'Prison Reform',
  'Public Health',
  'Race & Racism',
  'Rape & Sexual Assault',
  'Recycling',
  'Refugees',
  'Renewable Energy',
  'Sex Education',
  'Sexism',
  'Sikhism',
  'Substance Abuse',
  'Suicide',
  'Transportation',
  'Unemployment',
  'Violence',
  'Volunteering',
  'Voting Rights',
  'Water',
  'Womens Issues',
  'Workplace Issues/Violence',
  'Zero Waste',
  'Aerobics',
  'Amusement Parks',
  'Archery',
  'ATV Riding',
  'Backpacking',
  'Badminton (Playing)',
  'Ballooning',
  'Baseball (Playing)',
  'Basketball (Playing)',
  'Beach Games (Playing)',
  'Biking',
  'Billiards',
  'Bird Watching',
  'Blackjack',
  'BMX',
  'Board Games',
  'Boat Fishing',
  'Boating',
  'Bodyboarding / Boogieboarding',
  'BodyBuilding',
  'Book Clubs',
  'Bouldering',
  'Bow Hunting',
  'Boxing',
  'Bungee Jumping',
  'Camping',
  'Candlepin Bowling',
  'Canoeing',
  'Canyoning',
  'Caving',
  'Circuit Training',
  'Clay Pigeon Shooting',
  'Cliff Diving',
  'Climbing',
  'Cross Country Skiing',
  'Counseling',
  'Cricket',
  'Cross Country Running',
  'Cross Country Skiing',
  'Curling',
  'Cycling',
  'Dancing',
  'Darts',
  'Diet & Nutrition',
  'Disc Golf / Frisbee Golf',
  'Dodgeball',
  'Dog Sledding',
  'Drone Racing',
  'Elephant Safari',
  'Fencing',
  'Fishing',
  'Fitness Classes',
  'Fly Fishing',
  'Football',
  'Gliding',
  'Go-Karting',
  'Golfing',
  'Gymnastics',
  'Handball',
  'Hang Gliding',
  'Hiking',
  'Hockey',
  'Horse Riding',
  'Hot Air Ballooning',
  'Hunting',
  'Hurling',
  'Ice Climbing',
  'Ice Hockey',
  'Ice Skating',
  'Inline Skating',
  'Ironman Triathlon',
  'Jogging',
  'Judo',
  'Karate',
  'Kayaking',
  'Kickboxing',
  'Kite Flying',
  'Kitesurfing / Kiteboarding',
  'Lawn Bowling',
  'Marathons',
  'Massage Therapy',
  'Medical Care',
  'Meditation',
  'Microlighting',
  'Motocross',
  'Motor Racing',
  'Motorcycle Riding',
  'Mountain Biking',
  'Mountainboarding',
  'Mountaineering',
  'Museums',
  'Nature Walk',
  'Netball',
  'Non-Medical Services',
  'Orienteering',
  'Paddle Boarding',
  'Paintball',
  'Paragliding',
  'Paramotoring',
  'Parasailing',
  'Parkour',
  'Pet Training',
  'Photography',
  'Pilates',
  'Ping-Pong',
  'Poker',
  'Polo',
  'Pool/Billiards',
  'Power Walking',
  'Quad Biking',
  'Quad Roller Skating',
  'Racquetball',
  'Rallying',
  'River Rafting',
  'Road Cycling',
  'Rock Climbing',
  'Roller Derby',
  'Rollerblading',
  'Rowing',
  'Rugby',
  'Running',
  'Safari',
  'Sailing',
  'Salt Water Fishing',
  'Sandboarding',
  'Scuba Diving',
  'Shooting',
  'Skateboarding',
  'Skiing',
  'Skydiving',
  'Sledding',
  'Snorkeling',
  'Snowboarding',
  'Snowkiting',
  'Snowshoeing',
  'Softball',
  'Squash',
  'Stand Up Paddleboarding',
  'Surfing',
  'Swimming',
  'Table Tennis',
  'Taekwondo',
  'Tai Chi',
  'Team Games',
  'Telemark Skiing',
  'Tennis',
  'Tenpin Bowling',
  'Touch Football',
  'Tourism',
  'Track Cycling',
  'Trail Running',
  'Trampolining',
  'Traveling',
  'Tree Climbing',
  'Trekking',
  'Triathlon',
  'Tubing',
  'Ultimate Frisbee',
  'Video Gaming',
  'Volleyball',
  'Wake Boarding',
  'Walking',
  'Water Polo',
  'Waterskiing',
  'Weight Training',
  'White Water Rafting',
  'Wildlife Safari',
  'Wind Surfing',
  'Yoga',
  'Ziplining',
  'Zumba',
  'Car Care',
  'Art Classes',
  'Arts & Crafts',
  'Cleaning',
  'Coaching',
  'Birthday Meetups',
  'Child Care',
  'Cooking',
  'Coding Training',
  'Community Music Making',
  'Errands',
  'Dance Instruction',
  'Community Beautification',
  'Dish Washer',
  'Handyman Services',
  'Language Classes',
  'Community Gardening',
  'Help with Technology',
  'Life Coaching',
  'Community Service',
  'Home Decorating',
  'Martial Arts & Self Defense',
  'Helping the YING Community',
  'Home Improvement',
  'Math Classes',
  'Mural Painting',
  'House Painting',
  'Music Classes',
  'Park/Vacancy Clean Up',
  'House Sitting',
  'Personal Coaching',
  'Recycling',
  'Organizing or Filing',
  'Political Science Classes',
  'Social Activism',
  'Party Planning',
  'Science Education',
  'Social Organizing',
  'Pet Grooming',
  'Technology Education',
  'Interest Group/Clubs',
  'Pet Sitting',
  'Wellness Classes',
  'Volunteering',
  'Respite Care',
  'Writing Classes',
  'Voting & Poll Service',
  'Tutoring',
  'Furniture Assembly',
  'Minimalist Organization Expert',
  'Yard Work',
  'Gardening',
  'Packing Boxes',
  'Moving Help',
  'Plumbing',
  'Electrical',
  'Painting',
  'Art Exhibitions',
  'Ballet',
  'Baseball',
  'Basketball',
  'Beer Appreciation / Beer Tasting',
  'Book Clubs',
  'Cinema',
  'Comedy',
  'Community Theatre',
  'Concerts',
  'Cooking',
  'Dance Instruction',
  'DJ Services',
  'Film Festival',
  'Fine Dining',
  'Food Appreciation / Fine Dining',
  'Football',
  'Learn a new language',
  'Live Comedy',
  'Museums',
  'Music - Playing Musical Instruments',
  'Music Festivals',
  'Opera',
  'Performing Arts',
  'Poetry',
  'Singing',
  'Soccer',
  'Sports & Sports Events',
  'Theatre',
  'Wine Appreciation/Tasting',
  'Writing / Writing Clubs',
  'Zoos',
  'Zumba Instruction',
  'Salsa Instruction',
  'African Dance'
      'Accountants',
  'Administrative Work',
  'Alterations/Sewing/Decorating',
  'Angling',
  'Animal Rescue & Removal',
  'Animation',
  'Appliance Repair',
  'Appraisals - Antiques/Jewelry/Items',
  'Architects & Building Design',
  'Artwork/Murals',
  'Asbestos Removal',
  'Auction Services',
  'Auto Detailing',
  'Auto Inspection',
  'Auto Repair',
  'Baking',
  'Banking/Credit Unions',
  'Bartending',
  'Biohazard Remediation',
  'Blind Cleaning',
  'Boat Sales and Repair',
  'Bookkeeping',
  'Cabinet Making',
  'Cabinet Refacing/Restoration',
  'Camera Sales/Repair',
  'Car Alarm Installation',
  'Car Detailing',
  'Car Inspection',
  'Car Rental',
  'Car Repair',
  'Career Coach',
  'Carpentry',
  'Carpet Cleaning',
  'Carpet Sales/Installation/Repair',
  'Catering',
  'Ceiling Fans',
  'Cell Phone Repair',
  'Chef',
  'Child Care',
  'Childproofing',
  'Chimney Services',
  'Chiropractic Care',
  'Cleaning',
  'Coaching',
  'Computer Repair & Services',
  'Computer Sales',
  'Computer Training',
  'Consulting',
  'Copywriting',
  'Counseling',
  'Customer Service',
  'Day Spa - Skin & Body Care Services',
  'Decks & Porches',
  'Delivery Service',
  'Dental Care',
  'Dermatology',
  'Design Strategy',
  'Digital Design',
  'Digital Marketing',
  'DJ Services',
  'Dog Training',
  'Doors',
  'Drivers Education',
  'Dry Cleaning',
  'Drone Consulting',
  'Drywall',
  'Electrical Appliance Repair',
  'Electrical Maintenance',
  'Electrician',
  'Energy Efficiency Auditing',
  'Equipment Rental',
  'Errands',
  'Event Planning',
  'Excavating',
  'Executive Coaching',
  'Excel Spreadsheets',
  'Eye Care',
  'Federal Government Contracting',
  'Financial Planning',
  'Fitness Training',
  'Floor Cleaning/Polishing/Waxing',
  'Florists',
  'Framing',
  'Fulfillment Services',
  'Furniture - Sales & Repair',
  'Gardening/Landscaping',
  'Genealogy',
  'Generator Repair & Sales',
  'Graphic Design',
  'Greenhouses/Nurseries',
  'Gutter Services',
  'Hair Salons/Barbers',
  'Hair Styling',
  'Handymen',
  'Hardware & Home Improvement Stores',
  'Hardwood Flooring Sales/Installation/Refinishing',
  'Hauling',
  'Heating & A/C',
  'Heating Oil',
  'Herbalism',
  'Holiday Decorating',
  'Home Alarms',
  'Home Appraisals',
  'Home Automation',
  'Home Builders',
  'Home Inspection',
  'Home Staging',
  'HVAC',
  'IInsurance Agencies',
  'Interior Design & Decorating',
  'Internet Research',
  'Internet Service',
  'Ironing',
  'Jewelry Sales/Design/Repair',
  'Keynote Presentation',
  'Lamp Repair',
  'Landline Phone Service',
  'Landscaping',
  'Lawn & Yard Work',
  'Lawn Fertilization & Treatment',
  'Lead Generation',
  'Leaf Removal',
  'Leather & Vinyl Repair',
  'Leadership Training',
  'Legal Services Personal',
  'Legal Services Corporate',
  'Legal Services Family',
  'Legal Services Non Profit',
  'Life Coaching',
  'Lighting',
  'Linked In Profile guidance',
  'Limosine Service',
  'Locksmith',
  'Logo Design',
  'Mailing Service',
  'Make-Up',
  'Manicures/Nails',
  'Manual Labor',
  'Marble & Granite',
  'Masonry',
  'Massage',
  'Mechanic',
  'Medical Care',
  'Meditation Instruction',
  'Metal Fabrication & Restoration',
  'Microsoft Office',
  'Midwifery',
  'Mixing & Mastering',
  'Mold Testing & Remediation',
  'Motorcycle Repair',
  'Moving Services',
  'Music Instruction',
  'Music Production',
  'Musical Instrument Repair',
  'Nanny Services',
  'Nutritionist',
  'Notary',
  'Office Cleaning',
  'Office Equipment Repair',
  'Office Support',
  'Oriental Rug Cleaning',
  'Online learning',
  'Painting',
  'Personal Chef',
  'Personal Shopping',
  'Personal Training',
  'Pest Control/Exterminating',
  'Phone Repair',
  'Phone Sales',
  'Photo Editing',
  'Photocopy',
  'Photography',
  'Piano Tuning',
  'Plant Maintenance',
  'Plumbing',
  'Pool & Spa Service',
  'Post-Production',
  'Power Washing',
  'Power Point',
  'PR Services',
  'Pressure Washing',
  'Printing',
  'Private Investigation',
  'Private Investigation',
  'Product Installation',
  'Production Strategy',
  'Professional Organizer',
  'Proofreading',
  'Propane Sales/Services',
  'Property Management',
  'Public Relations',
  'Real Estate Agents',
  'React/React Native',
  'Remodeling',
  'Research',
  'Resume Services',
  'Roofing',
  'Roto-Tilling',
  'RV Sales & Service',
  'Sales Training',
  'Screenwriting',
  'Script Writing',
  'Sea Kayaking',
  'Seamstress/Tailor',
  'Secretarial Services',
  'Septic Tank',
  'Sewer Cleaning',
  'Sewing Machine Repair',
  'Sharing Economy Consulting',
  'Shipping',
  'Shoe Repair',
  'Siding',
  'Signs',
  'Snow Removal',
  'Social Media',
  'Software Development',
  'Solar Panels',
  'Skype Presentations',
  'Spa Services',
  'Special Events',
  'Staffing Agency',
  'Stereo & Home Theater Systems',
  'Stone & Gravel',
  'Tanning Salons',
  'Tattoos/Piercings',
  'Tax Consultants',
  'Tax Preparation',
  'Taxi/Shuttle Service',
  'Tech Installation',
  'Ticket Broker Service',
  'Toy Repair',
  'Training',
  'Translation Services',
  'Travel',
  'Travel Agency/Management',
  'Tree Service',
  'Truck Driver',
  'Tutoring',
  'TV Repair',
  'TV Sales',
  'Upholstering',
  'Upholstery Cleaning',
  'Vacuum Cleaners',
  'Veterenary Consultation',
  'Video',
  'Video Production',
  'Videographer',
  'Virtual Assistant',
  'YouTube Expert',
  'Wallpapering',
  'Wardrobe Stylist',
  'Watch Repair',
  'Water & Smoke Damage',
  'Water Heaters',
  'Waiting Tables',
  'Water Sports',
  'Web Design',
  'Web Development',
  'Wedding Planning',
  'Weight Loss',
  'Welding',
  'Whitewater Rafting',
  'Window Washing',
  'Windshield Repair',
  'Zoom Video'
      'Amateur Radio',
  'Animation',
  'Antiques/Antiquing',
  'Art',
  'Astrology',
  'Baking',
  'Basket Weaving',
  'Bead Making',
  'Beadwork',
  'Bird Watching',
  'Birds',
  'Board games',
  'Book Binding',
  'Butterfly Watching',
  'Calligraphy',
  'Camping',
  'Card Games',
  'Cardmaking',
  'Carpentry',
  'Cats',
  'Ceramics',
  'Checkers',
  'Chess',
  'Classic Cars',
  'Coin collecting',
  'Collage making',
  'Computer Games',
  'Cooking',
  'Crocheting',
  'Cross Country Trips',
  'Cross-stitching',
  'Dogs',
  'Drawing',
  'Electronics',
  'Embroidery',
  'Felting',
  'Fish',
  'Flower Arranging',
  'Furniture making',
  'Gardening',
  'Genealogy',
  'Glass Blowing',
  'Glass Craft',
  'Handmade Jewellery',
  'Henna Art',
  'Homebrewing',
  'Hot Rodding',
  'Illustration',
  'Karaoke',
  'Knitting',
  'Lace making',
  'Leather work',
  'Magic',
  'Mahjong',
  'Making Clothes',
  'Mask Making',
  'Meditation',
  'Metal Detecting',
  'Model Aircraft Flying',
  'Model Engineering',
  'Mosaics',
  'Needlepoint',
  'Painting',
  'Palmistry',
  'Patchwork',
  'Pets',
  'Photography',
  'Pottery',
  'Print making',
  'Printmaking',
  'Pub Quiz / Trivia Night',
  'Quilting',
  'Reptiles / Amphibians',
  'Scrabble',
  'Scrapbooking',
  'Sculpting',
  'Sewing',
  'Spinning Wool',
  'Sports Car Meets',
  'Tarot Card Reading',
  'Textiles',
  'Toy Making',
  'Travelling',
  'Volunteer Work',
  'Weaving',
  'Welding',
  'Wildlife Viewing',
  'Wood craft',
  'web design',
  'gardening',
  'automotive mechanic',
  'public speaking',
  'data analysis',
  'graphic design',
  'programming',
  'financial planning',
  'customer service',
  'photography',
  'foreign language proficiency',
  'project management',
  'content writing',
  'marketing',
  'problem-solving',
  'leadership',
  'critical thinking',
  'time management',
  'public relations',
  'networking',
  'social media management',
  'creative writing',
  'negotiation',
  'event planning',
  'research',
  'public health knowledge',
  'sales',
  'teaching',
  'mentoring',
  'conflict resolution',
  'emotional intelligence',
  'database management',
  'software development',
  'cybersecurity',
  'cloud computing',
  'artificial intelligence',
  'machine learning',
  'virtual collaboration',
  'data visualization',
  'public policy analysis',
  'business strategy',
  'financial analysis',
  'entrepreneurship',
  'video editing',
  'audio production',
  'game development',
  'animation',
  'meditation',
  'yoga',
  'nutrition',
  'culinary skills',
  'first aid',
  'interpersonal communication',
  'user experience (UX) design',
  'user interface (UI) design',
  'product management',
  'supply chain management',
  'logistics',
  'business analysis',
  'customer relationship management (CRM)',
  'data entry',
  'virtual assistance',
  'event coordination',
  'fundraising',
  'grant writing',
  'community organizing',
  'nonprofit management',
  'fundamental IT skills',
  'hardware troubleshooting',
  'network administration',
  'system security',
  'technical support',
  'creative thinking',
  'innovation',
  'self-motivation',
  'adaptability',
  'emotional resilience',
  'decision-making',
  'legal research',
  'courtroom advocacy',
  'mediation',
  'contract negotiation',
  'strategic planning',
  'risk management',
  'business development',
  'market research',
  'data analytics',
  'data interpretation',
  'quality assurance',
  'presentation skills',
  'writing',
  'editing',
  'proofreading',
  'content strategy',
  'SEO (Search Engine Optimization)',
  'digital marketing',
  'email marketing',
  'branding',
  'experimental design',
  'statistical analysis',
  'scientific writing',
  'laboratory techniques',
  'communication',
  'community engagement',
  'political strategy',
  'campaign management',
  'international relations',
  'cross-cultural communication',
  'journalism',
  'video production'
];
