import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: colorScheme.primaryContainer.withOpacity(1),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.h),
          ),
          shadowColor: colorScheme.onPrimary.withOpacity(0.1),
          elevation: 18,
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: colorScheme.onPrimary.withOpacity(0.12),
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      radioTheme: RadioThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: colorScheme.primaryContainer.withOpacity(0.12),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: colorScheme.onPrimary.withOpacity(0.12),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: colorScheme.onPrimary.withOpacity(0.42),
          fontSize: 16.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.onPrimary.withOpacity(0.42),
          fontSize: 14.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: colorScheme.onPrimary.withOpacity(0.42),
          fontSize: 12.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w400,
        ),
        headlineLarge: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 32.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        headlineMedium: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 28.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 24.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        labelLarge: TextStyle(
          color: colorScheme.onPrimary.withOpacity(0.42),
          fontSize: 12.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w500,
        ),
        labelMedium: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 11.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w600,
        ),
        labelSmall: TextStyle(
          color: colorScheme.primaryContainer.withOpacity(1),
          fontSize: 9.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w600,
        ),
        titleLarge: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 20.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: colorScheme.primaryContainer.withOpacity(1),
          fontSize: 16.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w600,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: 14.fSize,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w600,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF6236FF),
    primaryContainer: Color(0XB2FFFFFF),
    secondary: Color(0XB2FFFFFF),
    secondaryContainer: Color(0XFF433FF1),
    tertiary: Color(0XB2FFFFFF),
    tertiaryContainer: Color(0XFF433FF1),

    // Background colors
    background: Color(0XB2FFFFFF),

    // Surface colors
    surface: Color(0XB2FFFFFF),
    surfaceTint: Color(0X510E0E17),
    surfaceVariant: Color(0XFF433FF1),

    // Error colors
    error: Color(0X510E0E17),
    errorContainer: Color(0XFF37474F),
    onError: Color(0XFFE340EC),
    onErrorContainer: Color(0XB2FFFFFF),

    // On colors(text colors)
    onBackground: Color(0XFF3528D8),
    onInverseSurface: Color(0XFFE340EC),
    onPrimary: Color(0X510E0E17),
    onPrimaryContainer: Color(0XFF3528D8),
    onSecondary: Color(0XFF3528D8),
    onSecondaryContainer: Color(0X510E0E17),
    onTertiary: Color(0XFF3528D8),
    onTertiaryContainer: Color(0X510E0E17),

    // Other colors
    outline: Color(0X510E0E17),
    outlineVariant: Color(0XB2FFFFFF),
    scrim: Color(0XB2FFFFFF),
    shadow: Color(0X510E0E17),

    // Inverse colors
    inversePrimary: Color(0XB2FFFFFF),
    inverseSurface: Color(0X510E0E17),

    // Pending colors
    onSurface: Color(0XFF3528D8),
    onSurfaceVariant: Color(0X510E0E17),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // Blue
  Color get blueA200 => Color(0XFF4E8AF4);

  // BlueGray
  Color get blueGray100 => Color(0XFFD4D4D4);
  Color get blueGray200 => Color(0XFFAAAAC1);
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray50 => Color(0XFFE9EFF2);
  Color get blueGray700 => Color(0XFF455A64);

  // Cyan
  Color get cyan300 => Color(0XFF43D6E8);
  Color get cyan50 => Color(0XFFE4FAFC);
  Color get cyan700 => Color(0XFF0BA9A7);

  // DeepOrange
  Color get deepOrange600 => Color(0XFFF25722);
  Color get deepOrange700 => Color(0XFFEF3B17);
  Color get deepOrangeA700 => Color(0XFFD82F0F);

  // DeepPurple
  Color get deepPurple300 => Color(0XFF8881DD);

  // Gray
  Color get gray100 => Color(0XFFF5F5F7);
  Color get gray10001 => Color(0XFFF5F5F5);
  Color get gray10002 => Color(0XFFF3F3FC);
  Color get gray200 => Color(0XFFE7E7E7);
  Color get gray20001 => Color(0XFFECECEC);
  Color get gray300 => Color(0XFFE1E0ED);
  Color get gray30001 => Color(0XFFE0E0E0);
  Color get gray50 => Color(0XFFFAFAFA);
  Color get gray800 => Color(0XFF493E3C);
  Color get gray900 => Color(0XFF12131A);

  // Green
  Color get green200 => Color(0XFFA5F0AF);
  Color get green400 => Color(0XFF4FD471);
  Color get green40001 => Color(0XFF44C983);
  Color get green50 => Color(0XFFE4FCEA);
  Color get green500 => Color(0XFF45C366);
  Color get green800 => Color(0XFF1F7D3A);

  // Indigo
  Color get indigo300 => Color(0XFF8D8CD9);
  Color get indigo400 => Color(0XFF496AD0);
  Color get indigo500 => Color(0XFF4559BD);
  Color get indigo700 => Color(0XFF3E399B);
  Color get indigoA200 => Color(0XFF5D5FEF);
  Color get indigoA700 => Color(0XFF3E35E5);

  // Indigof
  Color get indigo4007f => Color(0X7F5F5EAC);

  // LightBlue
  Color get lightBlue50 => Color(0XFFE1F5FF);

  // Orange
  Color get orange400 => Color(0XFFFF9E2A);
  Color get orange40001 => Color(0XFFFF9129);
  Color get orange50 => Color(0XFFFFF4E6);

  // Pink
  Color get pink300 => Color(0XFFE05780);

  // Purple
  Color get purple400 => Color(0XFFBC36DE);
  Color get purple50 => Color(0XFFFEEAFE);
  Color get purple600 => Color(0XFF862CCA);
  Color get purpleA200 => Color(0XFFD23CE6);

  // Red
  Color get red50 => Color(0XFFFFEEEC);
  Color get red5001 => Color(0XFFFFEBF1);

  // Yellow
  Color get yellow800 => Color(0XFFF79E1B);
  Color get yellow900 => Color(0XFFFF8127);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
